train:
  _target_: src.datasets.LJspeechDataset
  part: "train"
  data_dir: "/kaggle/input/small-dataset-two/small_dataset"
val:
  _target_: src.datasets.LJspeechDataset
  part: "test"
  data_dir: "/kaggle/input/small-dataset-two/small_dataset"