defaults:
  - model: hifigan
  - writer: wandb
  - metrics: example
  - datasets: ljspeech
  - dataloader: example
  - transforms: no_transforms
  - _self_
inferencer:
  device_tensors: ["data_object", "labels"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "checkpoint-epoch19.pth" # path to the pretrained model

audio_dir: "audios"
transcription_dir: "/kaggle/input/texts-test/texts"
