_target_: src.logger.WandBWriter
project_name: "HIFIGAN project"
entity: null
run_name: "testing"
mode: "online"
loss_names: ["gen_loss", "feature_loss", "mel_loss", "total_loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: True # set to True if you want to log save_dir with checkpoints to W&B
id_length: 8 # length of the run_id
